spring:
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/server_db_0
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    open-in-view: false